version: '3.8'
services:
  db:
    image: postgres:15-alpine
    platform: linux/arm64
    environment:
      POSTGRES_USER: valkyrie
      POSTGRES_PASSWORD: valkyrie
      POSTGRES_DB: valkyrie
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    platform: linux/arm64
    volumes:
      - ./data/redis:/data

  api:
    build: .
    platform: linux/arm64
    environment:
      - VALKYRIE_DATABASE_URL=postgresql+psycopg://valkyrie:valkyrie@db:5432/valkyrie
      - VALKYRIE_REDIS_URL=redis://redis:6379/0
    ports:
      - 6789:6789
    depends_on:
      - db
      - redis

# Neo4j is optional and may not have arm64 images; if you need it, run on a separate machine or cloud instance.
# You can omit the neo4j service and rely on Redis-backed graph fallback implemented in the app.
