services:
  postgres:
    image: postgres:16-alpine
    container_name: odin-valkyrie-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/pos:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-valkyrie} -d ${POSTGRES_DB:-valkyrie}"]
      interval: 3s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    networks: [odinnet]

  backend:
    container_name: odin-valkyrie-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: ./.env
    volumes:
      - ./data/files:/files
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "6789:6789"
    restart: unless-stopped
    networks: [odinnet]
