version: "3.11"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odin-valkyrie-backend
    env_file:
      - .env
    ports:
      - "6789:6789"
    volumes:
      - ./files:/files
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      uvicorn backend.app.main:app
      --host 0.0.0.0
      --port 6789
      --reload
    networks:
      - odinnet

  postgres:
    image: postgres:16-alpine
    container_name: odin-valkyrie-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - odinnet

networks:
  odinnet:
    driver: bridge
